import Head from 'next/head';
import Image from 'next/image';
import Connect from '../components/Connect';
import Nav from '../components/Nav';
import Tabs from '../components/Tabs';
import { XIcon } from '@heroicons/react/solid';
import { useRef } from 'react';
import { useRouter } from 'next/router';
import { IAssetData } from './helpers/types';
import BalanceAsset from '../components/BalanceAsset';

export default function Home() {
	const router = useRouter();
	const searchInputRef = useRef(null);

	const {
		query: { tab },
	} = router;
	const isTabOne = tab === '1' || tab == null;
	const isTabTwo = tab === '2';
	const isTabThree = tab === '3';

	const search = (e) => {
		e.preventDefault();
		const term = searchInputRef.current.value;

		if (!term) return;
		router.push(`/?term=${term}`);
	};
	return (
		<div>
			<Head>
				<title>Jina</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{/* Header component */}
			{/* <header className='flex w-full p-5 justify-between text-sm text-gray-500'> */}
			{/* Left section */}
			{/* <div className='flex space-x-4 items-center'>
					<p className='link'>About</p>
					<p className='link'>Whitepaper</p>
				</div> */}
			{/* Right section */}
			{/* <Connect /> */}
			{/* </header> */}

			{/* Body component */}
			<form className='flex flex-col items-center mt-20 flex-grow'>
				{/* <Image
					src='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
					height={100}
					width={300}
				/> */}
				<Nav />

				{/* <Tabs color='blue' /> */}
				<form className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
					<p className='relative px-7 py-2 rounded-md leading-none flex items-center divide-x divide-gray-500'>
						<span className='pr-2 text-indigo-400 cursor-pointer hover:text-pink-600 transition duration-200'>
							MAX
						</span>
						{isTabOne && <span className='pl-2 text-gray-500'>ALGO</span>}
						{isTabTwo && <span className='pl-2 text-gray-500'>USDC</span>}
					</p>
					<input
						ref={searchInputRef}
						type='number'
						className='flex-grow focus:outline-none bg-[#FAFAFA]'
					/>
					<XIcon
						className='h-5 sm:mr-3 text-gray-500 cursor-pointer transition duration-100 transform hover:scale-125'
						onClick={() => (searchInputRef.current.value = '')}
					/>
					<button hidden type='submit' onClick={search}>
						Search
					</button>
				</form>
				<div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
					<button onClick={search} className='btn'>
						Borrow
					</button>
					<button onClick={search} className='btn'>
						Increase Collateral
					</button>
				</div>
			</form>
			{/* Footer */}
		</div>
	);
}
